name: Prune old Cloudflare Pages deployments
on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  prune:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CF_PAGES_PROJECT: ff14crafting
      KEEP_COUNT: "5"
    steps:
      - name: List and delete older deployments
        run: |
          set -euo pipefail
          URL="https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/pages/projects/$CF_PAGES_PROJECT/deployments?per_page=100"
          JSON=$(curl -fsSL -H "Authorization: Bearer $CF_API_TOKEN" "$URL")

          echo "Summary before prune:"
          echo "$JSON" | jq '{total: (.result|length), newest_ids: [.result[:env.KEEP_COUNT|tonumber][]|.id]}'

          ids_to_delete=$(echo "$JSON" | jq -r --argjson keep "$KEEP_COUNT" '.result[$keep:] | .[].id')

          for id in $ids_to_delete; do
            echo "Deleting deployment $id"
            curl -fsS -X DELETE -H "Authorization: Bearer $CF_API_TOKEN" \
              "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/pages/projects/$CF_PAGES_PROJECT/deployments/$id" >/dev/null
          done

          echo "Prune complete."
