name: Sync from upstream (main)
on:
  schedule: [{ cron: "0 2 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/KonaeAkira/raphael-rs.git || true
          git fetch upstream main

      - name: Configure committer
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge upstream/main -> main
        run: |
          git checkout main
          git merge --ff-only upstream/main || git merge --no-edit upstream/main

      - name: Push to origin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} main
